extend user and recipe schema add guards to create recipe and getUser…
luzuj-ponton/recipes pull request #12
Opened 2021-02-22 22:17 UTC by duch0416

…Recipes endpoints, add getUserRecipes endpoint

2021-02-22 22:24 UTC, marcinsobchuck approved these changes

2021-02-23 19:33 UTC, Adamwojty requested changes

2021-02-23 19:33 UTC, Adamwojty commented on packages/backend/src/recipes/recipes.controller.ts
> +  @Get('user/:id')
Moim zdaniem ten endpoint bardziej przyda się na zwracanie danych o użytkowniku jak będziemy robić profil użytkownika. Może recipes/user/:id?

2021-02-23 19:35 UTC, Adamwojty approved these changes

2021-02-23 19:35 UTC, merged