Feature/home page
luzuj-ponton/recipes pull request #21
Opened 2021-03-02 18:36 UTC by marcinsobchuck

2021-03-02 18:47 UTC, Adamwojty requested changes

2021-03-02 18:47 UTC, Adamwojty commented on packages/frontend/src/Views/Home/Home.styled.ts
> +export const Wrapper = styled.div``;
Po co ten plik?

2021-03-02 18:47 UTC, Adamwojty commented on packages/frontend/src/Layout/Newsletter/Newsletter.styled.ts
> +  ::placeholder {
:placeholder

2021-03-02 19:16 UTC, marcinsobchuck commented on packages/frontend/src/Layout/Newsletter/Newsletter.styled.ts
> +  ::placeholder {
https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder

2021-03-02 20:28 UTC, duch0416 commented on packages/frontend/src/Layout/Newsletter/Newsletter.styled.ts
> +  ::placeholder {
w styled components jest inaczej dajesz zazwyczaj jedne :

2021-03-02 20:31 UTC, duch0416 commented on packages/frontend/src/enums/maxWidth.enum.ts
> +export enum MaxWidth {
nazwij tego enuma gridWidth ? nazwa maxWidth mało mówi

2021-03-02 20:32 UTC, duch0416 commented on packages/frontend/src/components/Socials/Socials.types.ts
> +export interface SocialIconProps extends SocialsStyledProps {
to powinno extendować socialsInfo

2021-03-02 20:37 UTC, duch0416 commented on packages/frontend/src/components/Socials/Socials.types.ts
> +export interface SocialIconProps extends SocialsStyledProps {
ten typ jest chyba nieuzywany

2021-03-02 20:39 UTC, duch0416 approved these changes

2021-03-03 09:26 UTC, Adamwojty approved these changes

2021-03-03 12:16 UTC, merged