UI dla rejestracji i logowania
luzuj-ponton/recipes pull request #7
Opened 2021-02-07 10:41 UTC by Adamwojty

2021-02-07 10:43 UTC, Adamwojty commented on packages/frontend/src/components/Button/Button.tsx
> +  //Remove and use one from common.styled.ts??
IMHO ten komponent jest nie potrzebny. Używajmy tego z common.

2021-02-08 15:31 UTC, marcinsobchuck requested changes

2021-02-08 15:31 UTC, marcinsobchuck commented on packages/frontend/src/Layout/Layout.tsx
> +  const hideNavigaion = pathname === Routes.Login || pathname === Routes.Register;
hideNavigation

2021-02-08 16:40 UTC, marcinsobchuck approved these changes

2021-02-16 19:42 UTC, duch0416 approved these changes

2021-02-16 19:51 UTC, merged